# Server Configuration
server.port=8761

# Application Name
spring.application.name=service-registry

# Eureka Server Configurations
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Actuator Endpoints (Optional)
management.endpoints.web.exposure.include=*
