# ==========================================================
# APPLICATION
# ==========================================================

spring.application.name=product-service

server.port=8081

# ==========================================================
# POSTGRESQL
# ==========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/product_db

spring.datasource.username=postgres

spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================================
# HIKARI
# ==========================================================

spring.datasource.hikari.pool-name=ProductHikariPool

spring.datasource.hikari.maximum-pool-size=10

spring.datasource.hikari.minimum-idle=5

spring.datasource.hikari.connection-timeout=20000

spring.datasource.hikari.idle-timeout=30000

spring.datasource.hikari.max-lifetime=1800000

# ==========================================================
# JPA
# ==========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# Hibernate automatically detects PostgreSQL.
# No need to specify spring.jpa.database-platform.

# ==========================================================
# EUREKA CLIENT
# ==========================================================

eureka.client.enabled=true

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true

# ==========================================================
# ACTUATOR
# ==========================================================

management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always

management.endpoint.health.probes.enabled=true

management.health.livenessstate.enabled=true

management.health.readinessstate.enabled=true

# ==========================================================
# SWAGGER
# ==========================================================

springdoc.api-docs.enabled=true

springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.packages-to-scan=com.ecommerce.product.controller

springdoc.paths-to-match=/api/**

# ==========================================================
# LOGGING
# ==========================================================

logging.level.root=INFO

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.com.netflix.discovery=INFO

# ==========================================================
# Eureka Client
# ==========================================================



# ==========================================================
# RESILIENCE4J CIRCUIT BREAKER
# ==========================================================

resilience4j.circuitbreaker.instances.inventoryService.register-health-indicator=true

resilience4j.circuitbreaker.instances.inventoryService.sliding-window-size=5

resilience4j.circuitbreaker.instances.inventoryService.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.inventoryService.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.inventoryService.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.inventoryService.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.inventoryService.automatic-transition-from-open-to-half-open-enabled=true



# ==================================================
# RESILIENCE4J RETRY
# ==================================================

resilience4j.retry.instances.inventoryService.max-attempts=3

resilience4j.retry.instances.inventoryService.wait-duration=2s

resilience4j.retry.instances.inventoryService.enable-exponential-backoff=true

resilience4j.retry.instances.inventoryService.exponential-backoff-multiplier=2

# ============================================
# FEIGN TIMEOUT CONFIGURATION
# ============================================

spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=3000


# ==========================================================
# BULKHEAD CONFIGURATION
# ==========================================================

resilience4j.bulkhead.instances.inventoryService.max-concurrent-calls=10

resilience4j.bulkhead.instances.inventoryService.max-wait-duration=1s