# ==========================================================
# APPLICATION
# ==========================================================

spring.application.name=inventory-service
server.port=8084

# ==========================================================
# POSTGRESQL
# ==========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db?useSSL=false&serverTimezone=UTC
#spring.datasource.url=jdbc:postgresql://postgres:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================================
# HIKARI CONNECTION POOL
# ==========================================================

spring.datasource.hikari.pool-name=InventoryHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# ==========================================================
# JPA
# ==========================================================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# ======================
# Eureka Client
# ======================

eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=host.docker.internal
# ==========================================================
# ACTUATOR
# ==========================================================

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# ==========================================================
# LOGGING
# ==========================================================

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#####################################################
# Swagger
#####################################################

springdoc.api-docs.enabled=true

springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.packages-to-scan=com.ecommerce.inventory.controller

springdoc.paths-to-match=/api/**


logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG
logging.level.org.springframework.cloud.client.discovery=DEBUG